[package]
name = "mtproxy-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
parking_lot = "0.12"
heapless = "0.8"

[lints]
workspace = true
